CinemaProject/Controllers/BookingsController.cs
using CinemaProject.Helpers;
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace CinemaProject.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private readonly CinemaDbContext context;
        private string CurrentUserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

        public BookingsController(CinemaDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var items = context.Bookings.Where(x => x.UserId == CurrentUserId).ToList();
            return View(items);
        }

        public IActionResult Create()
        {
            var ids = HttpContext.Session.Get<List<int>>(Constants.cartItemsKey) ?? new();
            var movies = context.Movies.Where(x => ids.Contains(x.Id)).ToList();

            var booking = new Booking()
            {
                Date = DateTime.Now,
                UserId = CurrentUserId,
                Movies = movies,
                TotalPrice = movies.Sum(x => x.TicketPrice)
            };

            context.Bookings.Add(booking);
            context.SaveChanges();

            // clear cart items
            HttpContext.Session.Remove(Constants.cartItemsKey);

            return RedirectToAction("Index");
        }

        // Export order data
        public IActionResult ExportOrder(int bookingId)
        {
            var orderDetails = context.Bookings
                .FirstOrDefault(b => b.Id == bookingId);

            if (orderDetails == null)
            {
                return NotFound();
            }

            var fileContent = $"Order ID: {orderDetails.Id}\nDate: {orderDetails.Date}\nTotal Price: {orderDetails.TotalPrice}$";
            var fileBytes = Encoding.UTF8.GetBytes(fileContent);

            var contentType = "text/plain";
            var fileName = $"Order #{orderDetails.Id}.txt";


            return File(fileBytes, contentType, fileName);
        }
    }
}

CinemaProject/Controllers/CartController.cs
using CinemaProject.Helpers;
using DataAccess.Data;
using Microsoft.AspNetCore.Mvc;

namespace CinemaProject.Controllers
{
    public class CartController : Controller
    {
        private readonly CinemaDbContext context;

        public CartController(CinemaDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var ids = HttpContext.Session.Get<List<int>>(Constants.cartItemsKey) ?? new();

            var movies = context.Movies.Where(x => ids.Contains(x.Id)).ToList();

            return View(movies);
        }

        public IActionResult Add(int id)
        {
            var ids = HttpContext.Session.Get<List<int>>(Constants.cartItemsKey) ?? new();

            ids.Add(id);

            HttpContext.Session.Set(Constants.cartItemsKey, ids);

            return RedirectToAction("Index", "Home");
        }
    }
}

CinemaProject/Controllers/MoviesController.cs
using CinemaProject.Models;
using DataAccess.Data;
using DataAccess.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CinemaProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MoviesController : Controller
    {
        private readonly CinemaDbContext context;

        public MoviesController(CinemaDbContext context)
        {
            this.context = context;
        }

        private void LoadGenres()
        {
            this.ViewBag.Genres = new SelectList(context.Genres.ToList(), "Id", "Name");
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var movies = context.Movies.ToList();

            return View(movies);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LoadGenres();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            context.Movies.Add(movie);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpPut]
        public IActionResult Edit(int id)
        {
            var item = context.Movies.Find(id);

            if (item == null) return NotFound();

            LoadGenres();

            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            context.Movies.Update(movie);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var item = context.Movies.Find(id);

            if (item == null) return NotFound(); 

            context.Movies.Remove(item);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CinemaProject/Views/Shared/_Layout.cshtml
@using DataAccess.Data.Entities;
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-black text-white border-bottom mb-3 h-25" style="margin-left: 0; margin-right: 0; padding-left: 0; padding-right: 0;">
            <div class="container-fluid bg-black h-25">
                <div class="row align-items-center bg-black h-25">
                    @*<div class="col">
                        <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Cinema Project</a>
                    </div> *@
                    <h1 class="text-white">Dark Delights Cinema</h1>
                </div>
                <div class="navbar-collapse bg-black collapse d-sm-inline-flex justify-content-between h-25">
                    <ul class="navbar-nav text-white flex-grow-1 h-25">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Movies" asp-action="Index">Administration</a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Bookings" asp-action="Index">Bookings</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CinemaProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>